# aigents #

services:
  # --- ALMACENAMIENTO --- #
  # PORT RANGE 64**
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    environment:
      QDRANT__STORAGE__PATH: /qdrant/storage
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
      QDRANT__SERVICE__JWT_RBAC: ${QDRANT_JWT_RBAC}
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - ${VOLUME_STORAGE:-./.storage}/aigents/qdrant:/qdrant/storage
    networks:
      - aigents_network

volumes:
  qdrant:

networks:
  aigents_network:
    driver: bridge
