# aigents #

services:
  # --- STORAGE --- #
  # PORT RANGE 64**
  qdrant:
    image: qdrant/qdrant:latest
    container_name: aigents_qdrant
    environment:
      QDRANT__STORAGE__PATH: /qdrant/storage
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
      QDRANT__SERVICE__JWT_RBAC: ${QDRANT_JWT_RBAC}
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - ${VOLUME_STORAGE:-./.storage}/aigents/qdrant:/qdrant/storage
    networks:
      - aigents_network

  # PORT RANGE 90**
  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-07T23-21-09Z
    container_name: aigents_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'  # Port for S3 API
      - '9001:9001'  # Port for MinIO web console
    volumes:
      - ${VOLUME_STORAGE:-./.storage}/aigents/minio:/data
    networks:
      - aigents_network

volumes:
  qdrant:
  minio:

networks:
  aigents_network:
    driver: bridge
